// src/types/scheduled-task.types.ts

/**
 * Status of a scheduled task
 */
export enum TaskStatus {
  PENDING = 'pending',       // Task is scheduled, waiting for execution time
  RUNNING = 'running',       // Task is currently executing
  COMPLETED = 'completed',   // Task completed successfully
  FAILED = 'failed',         // Task failed with error
  CANCELLED = 'cancelled',   // Task was cancelled by user
  MISSED = 'missed',         // Task execution time passed while app was closed
}

/**
 * Represents a scheduled task (workflow execution at specific time)
 */
export interface ScheduledTask {
  id: string;                    // UUID v4
  workflowId: string;            // Reference to WorkflowLibraryItem.id
  workflowName: string;          // Cached workflow name for display
  scheduledTime: Date;           // When to execute this task
  status: TaskStatus;            // Current status
  createdAt: Date;               // When task was scheduled
  startedAt?: Date;              // When execution began
  completedAt?: Date;            // When execution finished
  promptId?: string;             // ComfyUI prompt_id (set during execution)
  error?: string;                // Error message if failed
  outputs?: TaskOutputs;         // Generated outputs
  retryCount: number;            // Number of retry attempts
  maxRetries: number;            // Maximum allowed retries
  priority: TaskPriority;        // Execution priority
}

/**
 * Priority levels for task execution
 */
export enum TaskPriority {
  LOW = 0,
  NORMAL = 1,
  HIGH = 2,
  URGENT = 3,
}

/**
 * Outputs generated by task execution
 */
export interface TaskOutputs {
  images?: string[];             // Array of image URLs
  videos?: string[];             // Array of video URLs
  metadata?: Record<string, unknown>; // Additional metadata from execution
}

/**
 * Input for creating a new scheduled task
 */
export interface CreateTaskInput {
  workflowId: string;
  scheduledTime: Date;
  priority?: TaskPriority;
  maxRetries?: number;
}

/**
 * Input for updating a scheduled task
 */
export interface UpdateTaskInput {
  scheduledTime?: Date;
  status?: TaskStatus;
  priority?: TaskPriority;
}

/**
 * Filter options for querying tasks
 */
export interface TaskFilterOptions {
  status?: TaskStatus | TaskStatus[];
  startDate?: Date;
  endDate?: Date;
  workflowId?: string;
}

/**
 * Statistics about tasks
 */
export interface TaskStatistics {
  total: number;
  pending: number;
  running: number;
  completed: number;
  failed: number;
  cancelled: number;
  missed: number;
}
